language: node_js
node_js:
  - "6"
  - "7"
sudo: false
install:
  - npm cache clean
  - npm install
notifications:
  email:
    on_success: never
    on_failure: always
before_script: "git clone https://github.com/sourcejs/init.git user"
script: npm run ci-test
