language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
sudo: false
notifications:
  email:
    on_success: never
    on_failure: always
before_script: "git clone https://github.com/sourcejs/init.git user"
script: npm run ci-test
