# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0.12

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

before_test: "git clone https://github.com/sourcejs/init.git user"

test_script:
  - node --version && npm --version
  - cmd: npm run ci-test

matrix:
  fast_finish: true

cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - node_modules -> package.json                                        # local npm modules